### ISSUE TITLE
Core data types and type classes should be Serializable

### ISSUE THREAD

**Issue by milessabin** [milessabin/shapeless#343]
In particular, `HList`, `Coproduct`, records, unions and the corresponding ops type classes.

**Comment by milessabin** [comment]
This is easy (ie. sprinkle `extends Serializable` everywhere), but there's a lot of it. If several people feel like taking part of the job on it would be a good idea to coordinate here to avoid duplicated effort.

**Comment by alexarchambault** [comment]
About `HList`, `Coproduct`, records, and unions, aren't they already? All their *instances* are case classes, which automatically implement `Serializable`.

**Comment by milessabin** [comment]
I think we also need the root traits to extend `Serializable`.

**Comment by milessabin** [comment]
One piece of good news: because the ops type classes are only implemented in shapeless and not by third parties it should be OK to not bother with specifying `SerialVersionUID` (observation due to @mpilquist).

**Comment by alexarchambault** [comment]
Why would root traits need to extend `Serializable`? Serializability is only needed for specific instances, and only at runtime.

**Comment by milessabin** [comment]
Fair comment, however see this ticket wrt `Either`: https://issues.scala-lang.org/browse/SI-9173.

**Comment by alexarchambault** [comment]
@milessabin Ok, It's a LUB issue then. (Serialization always worked.)

**Comment by milessabin** [comment]
Yup. I saw that come past in the context of lots of excitement around serializablity and Spark and put two and two together to make five ;-)

**Comment by ijuma** [comment]
@milessabin Can you please expand a bit on the reason why it's OK not to specify `SerialVersionUID` for type classes that are not implemented by third parties?

**Comment by milessabin** [comment]
I'm channeling @mpilquist,
> I think it is totally fair to say that shapeless types provide no serialization guarantees when the
> deserializing side uses a different shapeless version than the serializing side.
Happy to hear alternative views ...

**Comment by ijuma** [comment]
Is the idea that people will use serialization to send data for remoting, but not for storage? If so, I think it's acceptable if the effort to provide this guarantee is high. It does mean that people will find it harder to upgrade to new shapeless versions as the upgrade must happen in lockstep between different services.

**Comment by milessabin** [comment]
This is mainly about type class instances, which probably shouldn't be being serialized anyway.

`HList` and `Coproduct` are already case classes/objects, so I guess handled by default. And they're minimal, so unlikely to change representation between versions.

**Comment by milessabin** [comment]
See also serializability tests from Algebra here: https://github.com/non/algebra/blob/master/laws/src/main/scala/algebra/laws/Rules.scala#L12 /ht @non

**Comment by milessabin** [comment]
OK, I'm making a start on this now ... please could anyone else who's looking at it ping me.

**Comment by adelbertc** [comment]
Mostly been using Shapeless in conjunction with Spark SQL, using the `HList` bits to track schema and whatnot. Things that will need to be `Serializable`:

* `HList` and `HList` related operations - say we have a Spark SQL table of rows and they want to `map` over the rows with `L <: HList => A` - this may involve stuff like the `Mapped` and `Length` type class since Spark may want to close over the type class instances and send that over the wire
* `(Labelled)Generic` and `FromTraversable` - converting an untyped `Row` to a `P <: Product` will involve a `Generic.Aux[P, L, Out` and a `FromTraversable[L]`. If we had an `RDD[Row]` (which is what backs Spark SQL tables) and wanted to `map` over it to create an `RDD[P]` Spark will try to send that stuff over the wire

Will add more as I hit them.

On a related note, I am happy to help test out stuff against a Spark cluster.

**Comment by milessabin** [comment]
Thanks ... very much appreciated :-)

**Comment by milessabin** [comment]
Fixed in 57b1e0071c7ea7403cbfc19f4e1d9946e324853e.

**Comment by koertkuipers** [comment]
> I'm channeling @mpilquist,
> 
> > I think it is totally fair to say that shapeless types provide no serialization guarantees when the
> > deserializing side uses a different shapeless version than the serializing side.
> 
> Happy to hear alternative views ...

just FYI

we ran into this because our application uses shapeless 2.3.3 but spark comes bundled with shapeless 2.3.2.

spark classpath hell on executors is pretty typical. i am still not sure what version is supposed to take precedence in this case. i have given up trying to make sense of that.

anyhow the result is:

```
2019-08-08 15:31:21 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 1.0 (TID 1, xxx, executor 1): java.io.InvalidClassException: shapeless.ops.hlist$ZipWithKeys$$anon$109; local class incompatible: stream classdesc serialVersionUID = -3477923700078369027, local class serialVersionUID = 760073377414809744
```

fix was to make sure the exact same shapeless version is used by spark and by our application. since we wanted to use shapeless 2.3.3 we  recompiled spark with 2.3.3 and deployed that .
